# Get API Response
Repository: https://github.com/risan/bibit-reksadana

In [5]:
from urllib.request import urlopen
import json

url = "https://bibit-reksadana.vercel.app/api?buy_from_bibit=true&per_page=10000"
response = urlopen(url)
data_json = json.loads(response.read())
bibit_fund = data_json['data']
print(bibit_fund[0])

{'id': 13, 'symbol': 'RD13', 'name': 'ABF Indonesia Bond Index Fund', 'type': 'Obligasi', 'profile': '', 'tradeable': 1, 'notbuyable': 0, 'status': 1, 'dividend_date': None, 'robocategory': 'fixincome', 'bank_redeem': {'id': 38, 'name': 'HSBC INDONESIA', 'color': '#EF241C'}, 'currency_exchange': {'exchange_rate': 1, 'currency': 'IDR'}, 'is_has_dividend': False, 'min_asset': 1000000, 'minbuy': 1000000, 'minsell': 1000000, 'executive': {}, 'fee': {'subscription': {'value': 0, 'type': 'percent'}, 'redemption': {'value': 0, 'type': 'percent'}, 'transfer': {'value': 0, 'type': 'percent', 'currency': 'IDR'}}, 'asset': [{'name': 'Obligasi', 'percentage': 100}, {'name': 'Saham', 'percentage': 0}, {'name': 'Likuiditas', 'percentage': 0}], 'holding': [{'symbol': None, 'name': 'FR0078', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0087', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0068', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0059', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0056', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0082', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0086', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0081', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0083', 'annualDividend': 0, 'date': '2022-05-31'}, {'symbol': None, 'name': 'FR0070', 'annualDividend': 0, 'date': '2022-05-31'}], 'bank': [{'bank': 'BCA', 'id': 31, 'account': '4587484098', 'name': 'Reksa Dana Indeks ABF Indonesia Bond Index Fund'}], 'exitload': [], 'investment_manager': {'name': 'Bahana TCW Investment Management, PT', 'ojkCode': 'DX002', 'telepon': '+62 21 2505277', 'fax': '+62 21 2505279', 'email': 'sinar@bahana.co.id', 'url': 'www.sinar.bahanatcw.com'}, 'custodian_bank': {'name': 'HSBC INDONESIA', 'ojkCode': 'HSBC1'}, 'sharia': False, 'etf': True, 'index': True, 'is_instant_redemption': False, 'aum': {'value': 4976394292409, 'date': '2022-04-01'}, 'shareholders': [], 'expenseratio': {'percentage': 0.0021}, 'cagr': {'1y': 0.027228037888962664, '3y': 0.08665559845561677, '5y': 0.06910619640882198, '10y': 0.06663223972803856, 'all': 0.08842141884918764}, 'cagr_adjusted': {'1y': 0.027228037888962664, '3y': 0.08665559845561677, '5y': 0.06910619640882198, '10y': 0.06663223972803856, 'all': 0.08845634469372343}, 'simplereturn': {'1d': 0.0048012183863375135, '1m': 0.00403942853152417, '3m': -0.013928319552163781, 'ytd': -0.01102023810688213, '1y': 0.027228037888962664, '3y': 0.2831450871890777, '5y': 0.3967035383061508, '10y': 0.9061060687739935, 'all': 2.40878744721347}, 'changesvalue': {'1d': 223.01610000000073, '1m': 187.7734000000055, '3m': -659.2575999999972, 'ytd': -520.0779999999941, '1y': 1237.1273, '3y': 10299.073900000003, '5y': 13256.435100000002, '10y': 22186.913200000003, 'all': 32980.9732}, 'nav': {'date': '2022-06-03', 'value': 46672.9132}, 'riskprofile': 'Moderate', 'maxdrawdown': {'1y': -0.04352614386495168, '3y': -0.08500568958456078, '5y': -0.09618645836821305, '10y': -0.1650636557262417, 'all': -0.2760120415115265}, 'changesvalueaum': {'1m': 4992884618074, '3m': 4953125786063, '6m': 4955070537317, 'ytd': 4953125786063, '1y': 4473365354447, '3y': 4195048340258, '5y': 4071346297048, '10y': 4071346297048, 'all': 4071346297048}}

# Save JSON Response as CSV

In [6]:
import pandas as pd

df_bibit_fund_desc = pd.DataFrame(bibit_fund)
df_bibit_fund_desc.to_csv('data/fund_desc_in_bibit.csv', index=False)
df_bibit_fund_desc.head()

,id,symbol,name,type,profile,tradeable,notbuyable,status,dividend_date,robocategory,...,shareholders,expenseratio,cagr,cagr_adjusted,simplereturn,changesvalue,nav,riskprofile,maxdrawdown,changesvalueaum
0,13,RD13,ABF Indonesia Bond Index Fund,Obligasi,,1,0,1,None,fixincome,...,[],{'percentage': 0.0021},"{'1y': 0.027228037888962664, '3y': 0.086655598...","{'1y': 0.027228037888962664, '3y': 0.086655598...","{'1d': 0.0048012183863375135, '1m': 0.00403942...","{'1d': 223.01610000000073, '1m': 187.773400000...","{'date': '2022-06-03', 'value': 46672.9132}",Moderate,"{'1y': -0.04352614386495168, '3y': -0.08500568...","{'1m': 4992884618074, '3m': 4953125786063, '6m..."
1,66,RD66,Avrist Ada Kas Mutiara,Pasar Uang,,1,0,1,None,moneymarket,...,[],{'percentage': 0.0028},"{'1y': 0.028056934894332475, '3y': 0.045806252...","{'1y': 0.028056934894332475, '3y': 0.045806252...","{'1d': 6.143591082574673e-05, '1m': 0.00249420...","{'1d': 0.07999999999992724, '1m': 3.2400000000...","{'date': '2022-06-03', 'value': 1302.25}",Low,"{'1y': -0.0003239116184012847, '3y': -0.000323...","{'1m': 55580217795.93, '3m': 350715170552.64, ..."
2,68,RD68,Avrist Ada Saham Blue Safir,Saham,,1,0,1,None,equity,...,[],{'percentage': 0.015},"{'1y': 0.1635519299723629, '3y': 0.03303776255...","{'1y': 0.1635519299723629, '3y': 0.03303776255...","{'1d': 0.003757932428120725, '1m': -0.02918813...","{'1d': 4.240000000000009, '1m': -34.0499999999...","{'date': '2022-06-03', 'value': 1132.52}",High,"{'1y': -0.08762701242127546, '3y': -0.43908263...","{'1m': 499653110552.48, '3m': 460348988321.78,..."
3,70,RD70,Avrist Balanced Amar Syariah,Campuran,,1,0,1,None,NaN,...,[],{'percentage': 0.009},"{'1y': 0.06965044669962728, '3y': 0.0290139810...","{'1y': 0.06965044669962728, '3y': 0.0290139810...","{'1d': 0.0022304295608672753, '1m': 0.01161200...","{'1d': 2.4700000000000273, '1m': 12.7400000000...","{'date': '2022-06-03', 'value': 1109.88}",Moderate,"{'1y': -0.04161486492998323, '3y': -0.23079420...","{'1m': 21852350966.98, '3m': 21657353848.26, '..."
4,82,RD82,Avrist IDX30,Saham,,1,0,1,None,equity,...,[],{'percentage': 0.0149},"{'1y': 0.1502748999096677, '3y': 0.02287018054...","{'1y': 0.1502748999096677, '3y': 0.02287018054...","{'1d': 0.0037075601140488246, '1m': -0.0398153...","{'1d': 3.8099999999999454, '1m': -42.769999999...","{'date': '2022-06-03', 'value': 1031.44}",High,"{'1y': -0.09903088023731732, '3y': -0.44294340...","{'1m': 214128455294.59, '3m': 191798011230.95,..."

# Scraping NAV Fund History
https://sites.google.com/chromium.org/driver/

https://www.pasardana.id/fund/search

## Prepare Web Driver

In [27]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By

driver = webdriver.Chrome('../driver/chromedriver.exe')

C:\Users\Asus\AppData\Local\Temp\ipykernel_19700\431741424.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('driver/chromedriver.exe')

## Login to pasardana.id

In [28]:
with open('../data/user_pasardana.json') as f:
    user_pasardana = json.load(f)

driver.get('https://www.pasardana.id/login')
driver.find_element(
    by=By.XPATH, value='//*[@id="EmailAddress"]').send_keys(user_pasardana['email'])
driver.find_element(
    by=By.XPATH, value='//*[@id="Password"]').send_keys(user_pasardana['password'])
driver.find_element(
    by=By.XPATH, value='/html/body/div/main/div/div/div/section/form/div[4]/div/button').click()

## Scraping NAV History

In [2]:
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support import expected_conditions as EC

In [123]:
df_bibit_fund_desc = pd.read_csv('../data/fund_desc_in_bibit.csv')
bibit_fund_name = df_bibit_fund_desc['name']

for name in bibit_fund_name[86:]:
    delay_search = 3
    delay_history = 6

    # go to search fund path
    print(f'Scraping: {name}')
    driver.get('https://www.pasardana.id/fund/search')
    time.sleep(delay_search)
    driver.find_element(
        by=By.XPATH, value='/html/body/div/ui-view/ui-view/ui-view/main/div[1]/div/div[2]/div[3]/div[2]/form/div/input').send_keys(name)
    time.sleep(delay_search)
    driver.find_element(
        by=By.XPATH, value='//*[@id="jqxWidget"]/div[4]/div[2]/table/tbody/tr[1]/td[3]/a').click()

    try:
        WebDriverWait(driver, delay_history).until(EC.presence_of_element_located(
            (By.XPATH, '//*[text()="Download CSV"]'))).click()
        print("- Success!")
    except TimeoutException:
        print("- Loading took too much time!")

Scraping: Sucorinvest Equity Fund
- Success!
Scraping: Sucorinvest Flexi Fund
- Success!
Scraping: Sucorinvest Maxi Fund
- Success!
Scraping: Sucorinvest Money Market Fund
- Success!
Scraping: Sucorinvest Sharia Equity Fund
- Success!
Scraping: Sucorinvest Sharia Money Market Fund
- Success!
Scraping: Sucorinvest Sharia Sukuk Fund
- Success!
Scraping: Sucorinvest Stable Fund
- Success!
Scraping: TRAM Consumption Plus Kelas A
- Success!
Scraping: TRAM Infrastructure Plus
- Success!
Scraping: TRAM Strategic Plus
- Success!
Scraping: TRIM Dana Tetap 2
- Success!
Scraping: TRIM Kapital
- Success!
Scraping: TRIM Kapital Plus
- Success!

In [124]:
driver.quit()

## Move NAV History from Downloads Folder to Project

In [1]:
import re
import os
import shutil

In [140]:

download_dir = 'C:\\Users\\Asus\\Downloads\\'
regex = re.compile('nav.*\.csv')

file_name_nav = []
for root, dirs, files in os.walk(download_dir):
    for file in files:
        if regex.match(file):
            file_name_nav.append(file)

file_name_nav[:5]

['nav (1).csv', 'nav (10).csv', 'nav (11).csv', 'nav (12).csv', 'nav (13).csv']

In [142]:
target_dir = '../data/nav/'
if not os.path.isdir(target_dir):
    os.mkdir(target_dir)

for file in file_name_nav:
    shutil.move(download_dir + file, target_dir + file)

# Data Cleansing

In [31]:
import os
import pandas as pd

## List NAV file name

In [26]:
nav_dir = '../data/nav/'
nav_file_list = os.listdir(nav_dir)

## Cleansing NAV Datasets

In [86]:
def cleansing_nav(df):
    for i in range(len(df)):
        if pd.isna(df.iloc[i,1]):
            df.iloc[i,1] = df.iloc[i,2]
    df.iloc[:,0] = pd.to_datetime(df.iloc[:,0])
    df = df.iloc[:,[0,1]]
    df = df[df['DateTime'] >= pd.to_datetime('2021-01-01')]
    df = df.set_index('DateTime').resample('D', origin='2021-01-01').ffill()
    df = df.fillna(method='ffill')
    # df = df.iloc[list(range(0,len(df.index),7)),:]
    return df

In [87]:
is_first = True
for file in nav_file_list:
    if is_first:
        df_nav_bibit = pd.read_csv(nav_dir + file)
        df_nav_bibit = cleansing_nav(df_nav_bibit)
        is_first = False
        continue
    df_temp = pd.read_csv(nav_dir + file)
    df_temp = cleansing_nav(df_temp)
    # df_nav_bibit = pd.merge(df_nav_bibit, df_temp, left_index=True, right_index=True)
    # df_nav_bibit.join(df_temp)
    df_nav_bibit = pd.concat([df_nav_bibit, df_temp], axis=1)

df_nav_bibit.head()

,Avrist Ada Kas Mutiara,Batavia Dana Kas Maxima,Batavia Dana Obligasi Ultima,BATAVIA DANA SAHAM,BATAVIA DANA SAHAM SYARIAH,BNI-AM DANA LANCAR SYARIAH,BNI-AM DANA LIKUID,REKSA DANA BNI-AM DANA PENDAPATAN TETAP MAKARA INVESTASI,BNI-AM DANA PENDAPATAN TETAP SYARIAH ARDHANI,BNI-AM Dana Saham Inspiring Equity Fund,...,Sucorinvest Sharia Money Market Fund,Sucorinvest Sharia Sukuk Fund,Sucorinvest Stable Fund,TRAM CONSUMPTION PLUS KELAS A,TRAM INFRASTRUCTURE PLUS,TRAM STRATEGIC PLUS,TRIM Dana Tetap 2,TRIM Kapital,TRIM KAPITAL PLUS,ABF INDONESIA BOND INDEX FUND
DateTime,,,,,,,,,,,,,,,,,,,,,
2021-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-01-04,1246.96,1568.89,2906.99,59857.44,1869.13,1543.44,1653.60,1223.8611,1419.54,1049.7000,...,1170.34,NaN,1076.08,1772.49,1215.36,1800.20,2656.5053,9604.3462,3398.2686,45329.2281
2021-01-05,1247.13,1569.05,2903.90,59858.20,1859.26,1543.70,1654.02,1223.5279,1419.38,1048.9446,...,1170.52,NaN,1076.36,1778.97,1223.08,1795.66,2653.6134,9656.8022,3416.7256,45262.1332
2021-01-06,1247.19,1569.22,2900.56,58896.09,1829.19,1543.72,1653.89,1222.8033,1419.70,1033.3167,...,1170.70,NaN,1076.62,1755.21,1209.29,1791.74,2651.0492,9547.7719,3368.8701,45209.5264
2021-01-07,1247.27,1569.38,2898.47,59938.56,1871.61,1544.05,1653.86,1222.5012,1420.70,1043.2939,...,1170.87,NaN,1077.00,1784.74,1241.31,1787.44,2649.7758,9742.4986,3433.7200,45166.9271

In [88]:
df_nav_bibit = df_nav_bibit.iloc[list(range(0,len(df_nav_bibit.index),7)), :]
df_nav_bibit = df_nav_bibit.iloc[1:,:]
df_nav_bibit.head()

,Avrist Ada Kas Mutiara,Batavia Dana Kas Maxima,Batavia Dana Obligasi Ultima,BATAVIA DANA SAHAM,BATAVIA DANA SAHAM SYARIAH,BNI-AM DANA LANCAR SYARIAH,BNI-AM DANA LIKUID,REKSA DANA BNI-AM DANA PENDAPATAN TETAP MAKARA INVESTASI,BNI-AM DANA PENDAPATAN TETAP SYARIAH ARDHANI,BNI-AM Dana Saham Inspiring Equity Fund,...,Sucorinvest Sharia Money Market Fund,Sucorinvest Sharia Sukuk Fund,Sucorinvest Stable Fund,TRAM CONSUMPTION PLUS KELAS A,TRAM INFRASTRUCTURE PLUS,TRAM STRATEGIC PLUS,TRIM Dana Tetap 2,TRIM Kapital,TRIM KAPITAL PLUS,ABF INDONESIA BOND INDEX FUND
DateTime,,,,,,,,,,,,,,,,,,,,,
2021-01-10,1247.30,1569.46,2895.29,60371.875,1885.40,1544.065,1653.91,1220.7064,1419.60,1064.3614,...,1170.960,NaN,1077.45,1798.475,1252.320,1782.345,2645.85660,9829.44955,3465.09225,45082.16570
2021-01-17,1248.51,1570.66,2887.51,61726.570,1912.19,1544.820,1655.18,1213.9486,1413.58,1072.2311,...,1172.180,NaN,1079.49,1843.160,1302.510,1763.490,2635.32450,10196.48890,3574.09280,44796.86690
2021-01-24,1249.47,1571.70,2882.86,62205.385,1880.90,1545.815,1656.01,1212.9603,1410.84,1069.6713,...,1172.985,NaN,1081.57,1842.770,1304.335,1753.605,2631.68275,10208.40065,3565.02545,44661.28425
2021-01-31,1250.60,1572.88,2894.44,57235.300,1705.56,1547.970,1657.61,1217.3251,1414.25,989.8970,...,1174.000,NaN,1083.60,1693.750,1200.610,1762.920,2645.07660,9463.96150,3296.71950,44892.01450
2021-02-07,1251.54,1573.92,2905.68,59675.505,1783.45,1549.075,1659.17,1222.2845,1419.31,1028.2307,...,1175.065,NaN,1085.61,1768.905,1253.075,1775.770,2659.31205,9853.62710,3447.86950,45127.17605

In [89]:
df_nav_bibit.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 73 entries, 2021-01-10 to 2022-05-29
Freq: 7D
Data columns (total 99 columns):
 #   Column                                                    Non-Null Count  Dtype
---  ------                                                    --------------  -----
 0   Avrist Ada Kas Mutiara                                    73 non-null     float64
 1   Batavia Dana Kas Maxima                                   73 non-null     float64
 2   Batavia Dana Obligasi Ultima                              73 non-null     float64
 3   BATAVIA DANA SAHAM                                        73 non-null     float64
 4   BATAVIA DANA SAHAM SYARIAH                                73 non-null     float64
 5   BNI-AM DANA LANCAR SYARIAH                                73 non-null     float64
 6   BNI-AM DANA LIKUID                                        73 non-null     float64
 7   REKSA DANA BNI-AM DANA PENDAPATAN TETAP MAKARA INVESTASI  73 non-null     float64
 8   BNI-AM DANA PENDAPATAN TETAP SYARIAH ARDHANI              73 non-null     float64
 9   BNI-AM Dana Saham Inspiring Equity Fund                   73 non-null     float64
 10  BNI-AM Indeks IDX30                                       73 non-null     float64
 11  Avrist Ada Saham Blue Safir                               73 non-null     float64
 12  ITB Harmoni BNI-AM                                        73 non-null     float64
 13  BNI-AM Mahogany                                           73 non-null     float64
 14  SYARIAH BNP PARIBAS CAKRA SYARIAH USD KELAS RK1           73 non-null     float64
 15  BNP PARIBAS EKUITAS                                       73 non-null     float64
 16  BNP Paribas Greater China Equity Syariah USD Kelas RK1    73 non-null     float64
 17  BNP PARIBAS INFRASTRUKTUR PLUS                            73 non-null     float64
 18  BNP Paribas Omega                                         73 non-null     float64
 19  BNP PARIBAS PESONA                                        73 non-null     float64
 20  BNP Paribas Pesona Syariah                                73 non-null     float64
 21  Reksa Dana BNP Paribas Prima II Kelas RK1                 73 non-null     float64
 22  AVRIST BALANCED AMAR SYARIAH                              73 non-null     float64
 23  BNP PARIBAS PRIMA USD                                     73 non-null     float64
 24  BNP PARIBAS RUPIAH PLUS                                   73 non-null     float64
 25  BNP PARIBAS SOLARIS                                       73 non-null     float64
 26  BNP Paribas Sri Kehati                                    73 non-null     float64
 27  DANAMAS RUPIAH PLUS                                       73 non-null     float64
 28  DANAMAS STABIL                                            73 non-null     float64
 29  DANAREKSA INDEKS SYARIAH                                  73 non-null     float64
 30  DANAREKSA MAWAR KONSUMER 10 KELAS A                       73 non-null     float64
 31  Danareksa Melati Pendapatan Utama                         73 non-null     float64
 32  DANAREKSA SERUNI PASAR UANG II                            73 non-null     float64
 33  Avrist IDX30                                              73 non-null     float64
 34  DANAREKSA SERUNI PASAR UANG III                           73 non-null     float64
 35  Reksa Dana Eastspring IDR Fixed Income Fund Kelas A       73 non-null     float64
 36  Reksa Dana Eastspring Investments Cash Reserve Kelas A    73 non-null     float64
 37  EASTSPRING INVESTMENTS VALUE DISCOVERY KELAS A            73 non-null     float64
 38  EASTSPRING INVESTMENTS YIELD DISCOVERY KELAS A            73 non-null     float64
 39  Eastspring Syariah Fixed Income Amanah Kelas A            73 non-null     float64
 40  Eastspring Syariah Greater China Equity USD Kelas A       73 non-null     float64
 41  Jarvis Balanced Fund                                      73 non-null     float64
 42  Jarvis Money Market Fund                                  73 non-null     float64
 43  MAJORIS OBLIGASI UTAMA INDONESIA                          73 non-null     float64
 44  AVRIST PRIME BOND FUND                                    73 non-null     float64
 45  Majoris Pasar Uang Syariah Indonesia                      73 non-null     float64
 46  MAJORIS SAHAM ALOKASI DINAMIK INDONESIA                   73 non-null     float64
 47  Majoris Sukuk Negara Indonesia                            73 non-null     float64
 48  MAKARA PRIMA                                              73 non-null     float64
 49  Mandiri Indeks FTSE Indonesia ESG Kelas A                 2 non-null      float64
 50  MANDIRI INVESTA ATRAKTIF-SYARIAH                          73 non-null     float64
 51  MANDIRI INVESTA DANA SYARIAH                              73 non-null     float64
 52  Mandiri Investa Syariah Berimbang                         73 non-null     float64
 53  Mandiri Investasi Obligasi Nasional                       73 non-null     float64
 54  Mandiri Pasar Uang Syariah Ekstra                         73 non-null     float64
 55  BAHANA DANA LIKUID                                        73 non-null     float64
 56  Manulife Dana Kas II Kelas A                              73 non-null     float64
 57  Manulife Dana Kas Syariah                                 73 non-null     float64
 58  REKSA DANA MANULIFE DANA SAHAM KELAS A                    73 non-null     float64
 59  MANULIFE OBLIGASI NEGARA INDONESIA II KELAS A             73 non-null     float64
 60  MANULIFE OBLIGASI UNGGULAN KELAS A                        73 non-null     float64
 61  MANULIFE SAHAM ANDALAN                                    73 non-null     float64
 62  Reksa Dana Manulife Syariah Sektoral Amanah Kelas A       73 non-null     float64
 63  MANULIFE USD FIXED INCOME KELAS A                         73 non-null     float64
 64  PRINCIPAL CASH FUND                                       73 non-null     float64
 65  Principal Index IDX30 Kelas O                             73 non-null     float64
 66  Bahana Likuid Syariah Kelas G                             73 non-null     float64
 67  PRINCIPAL ISLAMIC EQUITY GROWTH SYARIAH                   73 non-null     float64
 68  PRINCIPAL TOTAL RETURN BOND FUND                          73 non-null     float64
 69  SCHRODER 90 PLUS EQUITY FUND                              73 non-null     float64
 70  SCHRODER DANA ISTIMEWA                                    73 non-null     float64
 71  Schroder dana Likuid                                      73 non-null     float64
 72  Schroder Dana Likuid Syariah                              73 non-null     float64
 73  SCHRODER DANA MANTAP PLUS II                              73 non-null     float64
 74  SCHRODER DYNAMIC BALANCED FUND                            73 non-null     float64
 75  SYARIAH SCHRODER GLOBAL SHARIA EQUITY FUND (USD)          73 non-null     float64
 76  SCHRODER SYARIAH BALANCED FUND                            73 non-null     float64
 77  REKSA DANA SYARIAH BAHANA MES SYARIAH FUND KELAS G        73 non-null     float64
 78  SCHRODER USD BOND FUND                                    73 non-null     float64
 79  SIMAS SAHAM UNGGULAN                                      73 non-null     float64
 80  Simas Satu                                                73 non-null     float64
 81  SIMAS SYARIAH UNGGULAN                                    73 non-null     float64
 82  REKSA DANA SUCORINVEST BOND FUND                          73 non-null     float64
 83  SUCORINVEST EQUITY FUND                                   73 non-null     float64
 84  SUCORINVEST FLEXI FUND                                    73 non-null     float64
 85  SUCORINVEST MAXI FUND                                     73 non-null     float64
 86  SUCORINVEST MONEY MARKET FUND                             73 non-null     float64
 87  SUCORINVEST SHARIA EQUITY FUND                            73 non-null     float64
 88  Bahana Primavera 99 Kelas G                               73 non-null     float64
 89  Sucorinvest Sharia Money Market Fund                      73 non-null     float64
 90  Sucorinvest Sharia Sukuk Fund                             31 non-null     float64
 91  Sucorinvest Stable Fund                                   73 non-null     float64
 92  TRAM CONSUMPTION PLUS KELAS A                             73 non-null     float64
 93  TRAM INFRASTRUCTURE PLUS                                  73 non-null     float64
 94  TRAM STRATEGIC PLUS                                       73 non-null     float64
 95  TRIM Dana Tetap 2                                         73 non-null     float64
 96  TRIM Kapital                                              73 non-null     float64
 97  TRIM KAPITAL PLUS                                         73 non-null     float64
 98  ABF INDONESIA BOND INDEX FUND                             73 non-null     float64
dtypes: float64(99)
memory usage: 57.0 KB

In [90]:
# Save NAV from Bibit fund list
df_nav_bibit.to_csv('../data/nav_bibit.csv')

## Get Stock Fund

In [79]:
import pandas as pd

In [136]:
df_fund_desc_bibit = pd.read_csv('../data/fund_desc_in_bibit.csv')
df_nav_bibit = pd.read_csv('../data/nav_bibit.csv')
df_nav_bibit = df_nav_bibit.set_index('DateTime')

In [137]:
# fund_condition = (df_fund_desc_bibit['type'] == 'Saham') & (df_fund_desc_bibit['minbuy'] == 10000)
fund_condition = (df_fund_desc_bibit['type'] == 'Saham')
df_nav_bibit.columns = [col.lower() for col in df_nav_bibit.columns]
stock_fund_list = [fund.lower() for fund in df_fund_desc_bibit[fund_condition]['name']]
df_nav_bibit_stock = df_nav_bibit[stock_fund_list]
df_nav_bibit_stock

,avrist ada saham blue safir,avrist idx30,bahana primavera 99 kelas g,batavia dana saham,batavia dana saham syariah,bni-am dana saham inspiring equity fund,bni-am indeks idx30,bni-am mahogany,bnp paribas ekuitas,bnp paribas infrastruktur plus,...,schroder dana istimewa,simas saham unggulan,simas syariah unggulan,sucorinvest equity fund,sucorinvest maxi fund,sucorinvest sharia equity fund,tram consumption plus kelas a,tram infrastructure plus,trim kapital,trim kapital plus
DateTime,,,,,,,,,,,,,,,,,,,,,
2021-01-10,1015.200,936.435,1257.22,60371.875,1885.40,1064.3614,900.31,911.800,18175.225,3028.345,...,7215.585,1346.59320,750.15765,2389.210,1745.28,1992.46,1798.475,1252.320,9829.44955,3465.09225
2021-01-17,1041.030,955.400,1260.60,61726.570,1912.19,1072.2311,907.22,929.420,18499.910,3093.370,...,7409.270,1373.71390,760.25800,2445.260,1745.15,2042.42,1843.160,1302.510,10196.48890,3574.09280
2021-01-24,1046.045,969.155,1261.40,62205.385,1880.90,1069.6713,912.37,933.910,18579.115,3094.920,...,7293.560,1358.49095,736.77840,2437.930,1741.17,2046.32,1842.770,1304.335,10208.40065,3565.02545
2021-01-31,954.140,879.540,1159.79,57235.300,1705.56,989.8970,833.24,855.480,17023.800,2826.150,...,6732.740,1251.07000,666.32520,2215.220,1617.16,1874.98,1693.750,1200.610,9463.96150,3296.71950
2021-02-07,993.195,915.870,1208.51,59675.505,1783.45,1028.2307,868.95,889.125,17698.045,2953.535,...,7005.545,1304.31885,697.78700,2325.455,1686.77,1933.04,1768.905,1253.075,9853.62710,3447.86950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-01,1157.340,1068.205,1341.47,66630.575,1926.80,1127.6916,1006.72,1065.555,19404.115,3178.850,...,7381.195,1427.21120,624.17620,2782.920,1866.27,2104.30,1987.290,1417.970,12239.07500,4401.75000
2022-05-08,1157.340,1068.205,1341.47,66630.575,1926.80,1127.6916,1006.72,1065.555,19404.115,3178.850,...,7381.195,1427.21120,624.17620,2782.920,1866.27,2104.30,1987.290,1417.970,12239.07500,4401.75000
2022-05-15,1080.130,984.775,1239.27,60408.515,1824.37,1051.7339,922.71,996.325,17880.930,2870.895,...,6766.965,1304.46935,593.77300,2724.105,1840.71,2125.48,1812.990,1300.190,11244.51500,4020.88500
2022-05-22,1100.360,1002.690,1274.72,63135.930,1869.29,1070.4770,939.21,1030.230,18324.830,3006.200,...,7044.430,1332.30160,604.73660,2805.910,1902.15,2146.21,1887.280,1343.830,11525.13000,4125.89000
2022-05-29,1118.720,1020.580,1298.84,63771.500,1871.46,1083.3627,955.37,1041.590,18571.210,3027.530,...,7156.310,1349.38380,608.45590,2838.760,1924.71,2118.84,1909.480,1355.010,11671.48000,4173.19000

In [138]:
df_nav_bibit_stock_ret = df_nav_bibit_stock.pct_change()
df_nav_bibit_stock_ret = df_nav_bibit_stock_ret.iloc[1:,:]
df_nav_bibit_stock_ret.head()

,avrist ada saham blue safir,avrist idx30,bahana primavera 99 kelas g,batavia dana saham,batavia dana saham syariah,bni-am dana saham inspiring equity fund,bni-am indeks idx30,bni-am mahogany,bnp paribas ekuitas,bnp paribas infrastruktur plus,...,schroder dana istimewa,simas saham unggulan,simas syariah unggulan,sucorinvest equity fund,sucorinvest maxi fund,sucorinvest sharia equity fund,tram consumption plus kelas a,tram infrastructure plus,trim kapital,trim kapital plus
DateTime,,,,,,,,,,,,,,,,,,,,,
2021-01-17,0.025443,0.020252,0.002688,0.022439,0.014209,0.007394,0.007675,0.019324,0.017864,0.021472,...,0.026843,0.020140,0.013464,0.023460,-0.000074,0.025075,0.024846,0.040078,0.037341,0.031457
2021-01-24,0.004817,0.014397,0.000635,0.007757,-0.016363,-0.002387,0.005677,0.004831,0.004281,0.000501,...,-0.015617,-0.011082,-0.030884,-0.002998,-0.002281,0.001909,-0.000212,0.001401,0.001168,-0.002537
2021-01-31,-0.087860,-0.092467,-0.080553,-0.079898,-0.093221,-0.074578,-0.086730,-0.083980,-0.083713,-0.086842,...,-0.076892,-0.079074,-0.095623,-0.091352,-0.071222,-0.083731,-0.080867,-0.079523,-0.072924,-0.075261
2021-02-07,0.040932,0.041306,0.042008,0.042635,0.045668,0.038725,0.042857,0.039329,0.039606,0.045074,...,0.040519,0.042563,0.047217,0.049763,0.043045,0.030966,0.044372,0.043699,0.041174,0.045849
2021-02-14,0.000780,-0.000420,-0.005751,0.005811,0.005680,-0.003415,-0.002002,0.004100,0.003340,0.001386,...,0.021980,0.012165,-0.006130,-0.005906,0.023450,0.008024,0.006024,0.008667,0.007270,0.006113

In [140]:
df_nav_bibit_stock_ret.to_csv('../data/nav_bibit_fund_return.csv')

## Split NAV dataset to train and test dataset

In [141]:
import pandas as pd
df_bibit = pd.read_csv('../data/nav_bibit_fund_return.csv')
df_bibit['DateTime'] = pd.to_datetime(df_bibit['DateTime'])
df_bibit.head()

,DateTime,avrist ada saham blue safir,avrist idx30,bahana primavera 99 kelas g,batavia dana saham,batavia dana saham syariah,bni-am dana saham inspiring equity fund,bni-am indeks idx30,bni-am mahogany,bnp paribas ekuitas,...,schroder dana istimewa,simas saham unggulan,simas syariah unggulan,sucorinvest equity fund,sucorinvest maxi fund,sucorinvest sharia equity fund,tram consumption plus kelas a,tram infrastructure plus,trim kapital,trim kapital plus
0,2021-01-17,0.025443,0.020252,0.002688,0.022439,0.014209,0.007394,0.007675,0.019324,0.017864,...,0.026843,0.020140,0.013464,0.023460,-0.000074,0.025075,0.024846,0.040078,0.037341,0.031457
1,2021-01-24,0.004817,0.014397,0.000635,0.007757,-0.016363,-0.002387,0.005677,0.004831,0.004281,...,-0.015617,-0.011082,-0.030884,-0.002998,-0.002281,0.001909,-0.000212,0.001401,0.001168,-0.002537
2,2021-01-31,-0.087860,-0.092467,-0.080553,-0.079898,-0.093221,-0.074578,-0.086730,-0.083980,-0.083713,...,-0.076892,-0.079074,-0.095623,-0.091352,-0.071222,-0.083731,-0.080867,-0.079523,-0.072924,-0.075261
3,2021-02-07,0.040932,0.041306,0.042008,0.042635,0.045668,0.038725,0.042857,0.039329,0.039606,...,0.040519,0.042563,0.047217,0.049763,0.043045,0.030966,0.044372,0.043699,0.041174,0.045849
4,2021-02-14,0.000780,-0.000420,-0.005751,0.005811,0.005680,-0.003415,-0.002002,0.004100,0.003340,...,0.021980,0.012165,-0.006130,-0.005906,0.023450,0.008024,0.006024,0.008667,0.007270,0.006113

In [142]:
df_bibit_train = df_bibit[df_bibit['DateTime'] < pd.to_datetime('2022-01-01')]
df_bibit_train.tail()

,DateTime,avrist ada saham blue safir,avrist idx30,bahana primavera 99 kelas g,batavia dana saham,batavia dana saham syariah,bni-am dana saham inspiring equity fund,bni-am indeks idx30,bni-am mahogany,bnp paribas ekuitas,...,schroder dana istimewa,simas saham unggulan,simas syariah unggulan,sucorinvest equity fund,sucorinvest maxi fund,sucorinvest sharia equity fund,tram consumption plus kelas a,tram infrastructure plus,trim kapital,trim kapital plus
45,2021-11-28,-0.012700,-0.011900,-0.026050,-0.021482,-0.008658,-0.030156,-0.021359,-0.019655,-0.022420,...,-0.029081,-0.027839,-0.026642,0.000837,0.002072,-0.004935,-0.019613,-0.021085,-0.017857,-0.023764
46,2021-12-05,0.002505,0.004537,0.000966,0.005386,0.009874,-0.002279,-0.001241,0.005999,0.006762,...,-0.001428,-0.005794,-0.003201,-0.003659,-0.018451,-0.023063,0.002277,0.002705,0.006027,0.004358
47,2021-12-12,0.006016,0.003462,0.010553,0.016081,0.017241,0.011297,0.010055,0.018794,0.007203,...,0.024513,0.007502,0.014597,0.018768,0.039341,0.012854,0.021640,0.028308,0.023736,0.025408
48,2021-12-19,-0.011969,-0.011105,-0.012630,-0.002956,-0.009560,-0.013356,-0.010231,0.002407,-0.012514,...,-0.014792,-0.012431,-0.024661,-0.005196,0.012562,0.001803,-0.004523,-0.004425,-0.006604,-0.009810
49,2021-12-26,-0.007563,-0.008062,-0.006544,-0.002427,-0.004292,-0.003184,-0.008966,0.009579,-0.006697,...,0.002242,-0.012850,-0.003243,-0.005503,-0.023500,-0.018880,0.001862,0.001837,0.000080,-0.001753

In [147]:
df_bibit_train.mean()[(df_bibit_train.mean() > 0)]

C:\Users\Asus\AppData\Local\Temp\ipykernel_13932\2823920664.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df_bibit_train.mean()[(df_bibit_train.mean() > 0)]

bni-am mahogany                                   0.000734
eastspring investments value discovery kelas a    0.000783
manulife saham andalan                            0.003653
simas saham unggulan                              0.000393
sucorinvest equity fund                           0.001108
sucorinvest maxi fund                             0.000466
sucorinvest sharia equity fund                    0.000102
tram consumption plus kelas a                     0.000081
tram infrastructure plus                          0.000460
trim kapital                                      0.001770
trim kapital plus                                 0.002122
dtype: float64

In [145]:
df_bibit_train.mean()[(df_bibit_train.mean() > 0)]

C:\Users\Asus\AppData\Local\Temp\ipykernel_13932\2823920664.py:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df_bibit_train.mean()[(df_bibit_train.mean() > 0)]

bni-am mahogany                                   0.000734
eastspring investments value discovery kelas a    0.000783
manulife saham andalan                            0.003653
simas saham unggulan                              0.000393
sucorinvest equity fund                           0.001108
sucorinvest maxi fund                             0.000466
sucorinvest sharia equity fund                    0.000102
tram consumption plus kelas a                     0.000081
tram infrastructure plus                          0.000460
trim kapital                                      0.001770
trim kapital plus                                 0.002122
dtype: float64

In [132]:
df_bibit_test = df_bibit[df_bibit['DateTime'] >= pd.to_datetime('2022-01-01')]
df_bibit_test.head()

,DateTime,batavia dana saham,batavia dana saham syariah,bni-am dana saham inspiring equity fund,bni-am indeks idx30,bni-am mahogany,bnp paribas pesona syariah,bnp paribas sri kehati,reksa dana manulife dana saham kelas a,simas saham unggulan
50,2022-01-02,-0.003327,-0.000643,-0.010660,-0.001254,-0.000128,0.002603,-0.000275,-0.003896,-0.001154
51,2022-01-09,0.014844,0.020589,0.019437,0.022483,0.011056,0.007675,0.018537,0.014851,0.014633
52,2022-01-16,-0.006556,-0.020327,0.000675,0.003741,-0.003464,-0.007723,0.006938,-0.004334,-0.013221
53,2022-01-23,0.004917,0.011773,0.002431,0.007500,-0.005375,0.004235,0.007096,0.003929,-0.003592
54,2022-01-30,-0.017441,-0.017672,-0.013328,-0.010985,-0.024967,-0.014727,-0.007981,-0.016444,-0.025259

In [146]:
df_bibit_train.to_csv('../data/nav_bibit_fund_return_train.csv', index=False)
df_bibit_test.to_csv('../data/nav_bibit_fund_return_test.csv', index=False)

# Save Market Return (JCI)

In [8]:
import pandas as pd

In [32]:
# IHSG from 2021-01-10 to 2021-12-31 in weekly
df_ihsg = pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/%5EJKSE?period1=1610236800&period2=1640908800&interval=1wk&events=history&includeAdjustedClose=true')
df_ihsg = df_ihsg.set_index(df_ihsg['Date'])
df_ihsg = df_ihsg.drop(columns='Date')
df_ihsg.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2021-01-11,6278.413086,6472.312012,6278.374023,6373.412109,6373.412109,1527600500
2021-01-18,6365.025879,6504.992188,6283.312988,6307.126953,6307.126953,1081229300
2021-01-25,6322.519043,6322.727051,5825.291992,5862.352051,5862.352051,813369600
2021-02-01,5856.776855,6179.368164,5735.469238,6151.729004,6151.729004,872980000
2021-02-08,6193.550781,6286.291016,6157.134766,6222.520996,6222.520996,563483000

In [33]:
df_ihsg_close_ret = df_ihsg['Close'].pct_change()
df_ihsg_close_ret = df_ihsg_close_ret.dropna()
df_ihsg_close_ret.head()

Date
2021-01-18   -0.010400
2021-01-25   -0.070519
2021-02-01    0.049362
2021-02-08    0.011508
2021-02-15    0.001512
Name: Close, dtype: float64

In [34]:
df_ihsg_close_ret.to_csv('../data/ihsg_close_return.csv')